### ISSUE TITLE
Sorting_by_actual_quantity_is_crashing_msupply_mobile

### ISSUE THREAD

**Issue by anildahalsussol** [sussol/mobile#631] opened 2018-03-14 06:41 UTC
Build Number: 2.1.0-rc8

Description:When i was testing msupply mobile and pressed the actual quantity in stock take msupply mobile gets crashed. I dont know whether we need to sort by actual quantity or not but it was clickable so while clicking its crashed the msupply  mobile.

Reproducible:just create new stock take and click the actual quantity.

Reproduction Steps:Create stock take or open any other stock take.Then try to sort by actual quantity then msupply will crash.

Comments:

**Comment by Chris-Petty** [comment] 2018-03-15 04:26
Duplicate of #617 

@anildahalsussol What wrong with spaces in the title haha?

**Closed by Chris-Petty** 2018-03-15 04:26 UTC

**Comment by anildahalsussol** [comment] 2018-03-15 04:31
@Chris-Petty : haha sorry ,Nothing but got habit writing in github. Will follow the standard system ...
