### ISSUE TITLE
New mobile version won't sync name/item records from server

### ISSUE THREAD

**Issue by adrianwb** [sussol/mobile#467] opened 2017-08-16 13:59 UTC
Build Number: debug build from inter-store requisitions branch

Description: Generates sync error on incoming sync records for names & items (perhaps others as well)

Reproducible:

Reproduction Steps: Edit any name/item on the primary - this will generate a sync record for all sites

Comments: Sync breaks until the offending sync record is removed from the outgoing queue on the server

**Comment by edmofro** [comment] 2017-08-17 04:33
@adrianwb I can't reproduce this...I suspect you built from the wrong branch? We had been using 'inter-store-requisitions-current'. Very confusing, I know. Anyway, it's all merged into master now, so hopefully you can get back to us on whether it's ok using master?

**Comment by edmofro** [comment] 2017-08-17 08:57
What I am experiencing though @adrianwb, and this is not consistent or probably related to your bug, is that some names aren't syncing down at all. In particular, stores on other sync sites don't seem to be reliably syncing to a given mSupply Mobile site. I haven't investigated, but it has happened twice for me, but having cleared and resynced they have synced normally. Not sure...but could be a major!

**Comment by edmofro** [comment] 2017-08-17 08:57
Btw @adrianwb, we are now working off the branch inter-store-requisition-cleanup

**Comment by adrianwb** [comment] 2017-08-17 10:41
@edmofro As a newbie to building mobile from source, it is indeed quite likely that I did something wrong, but I'm now on inter-store-requisition-cleanup branch and it looks like names/items are syncing ok from the server. I'll see if I can find anything on store name syncing.

**Comment by adrianwb** [comment] 2017-08-17 11:00
@edmofro I've tried editing store names on the server (e.g. DS Baucau) and the name change seems to propagate fine to mobile running Baucau referral hospital. The sync record for the DS Baucau [store] itself gets filtered out along with any  other sync records which are for a different store than the mobile site's own store, but the sync record for the DS Baucau [name] goes through. If mobile also needs to have updates for [store] records for other stores, then I can tweak that on the server side - let me know.

**Comment by andreievg** [comment] 2017-08-17 13:15
@adrianwb yes, mobile ignores store records coming through sync so no reason to worry about creating new sync_out records for them.

**Comment by edmofro** [comment] 2017-08-18 06:33
Closing this, pretty sure discussion above has resolved it.

**Comment by Chris-Petty** [comment] 2017-08-18 08:48
Seems to be occurring in our training, will follow up with a close if it isn't our setup.

**Comment by Chris-Petty** [comment] 2017-08-18 14:05
Was our set up 👍

**Closed by Chris-Petty** 2017-08-18 14:05 UTC
Labels: Bug, Priority: High

**Comment by andreievg** [comment] 2017-08-18 14:06
So .. had a problem during a presentation.. no name syncing. But sorted now.
Make sure to have both stores as TRANSFER FOR EACH OTHER in special->stores->sync
