### ISSUE TITLE
'Not counted' remains in stocktake column when same amount is entered

### ISSUE THREAD

**Issue by michaelnunan** [sussol/mobile#579] opened 2017-12-11 02:42 UTC
In the latest version, when you're doing a stocktake and you enter an actual amount that is the same as the snapshot amount, the cell automatically reverts to say 'Not Counted'. 
Whilst I realise why it's doing this (because it will make no change, so it's literally not doing a stock adjustment with it), it's misleading, particularly when multiple people are working on a stocktake and ESPECIALLY when you're jumping around items (not ideal practice but happens a lot).
It would be better to keep the entered amount appearing in the cell or revert it to 'No Change' rather than jumping back to 'Not Counted'. In our most recent stocktake, people repeatedly got confused, returned to lines and counted them again.

**Comment by andreievg** [comment] 2017-12-11 05:20
Fixed in https://github.com/sussol/mobile/pull/580

This should have been the default behaviour

**Comment by Chris-Petty** [comment] 2017-12-11 20:46
Duplicate of #575

**Closed** 2017-12-13 21:44 UTC
