### ISSUE TITLE
TypeError in index.android.bundle:747

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#709] opened 2018-08-08 20:39 UTC
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:747**
null is not an object (evaluating 'e.itemBatch.id')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5b6b54ebb94c08001af85c6a?event_id=5b6b54eb002acc55a6860000&i=gh&m=ci)

## Stacktrace

    index.android.bundle:747 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5b6b54ebb94c08001af85c6a?event_id=5b6b54eb002acc55a6860000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment] 2018-10-08 03:31
Good chance this is a duplicate of #711 but the bugsnag is 404 here, so closing.

**Closed by Chris-Petty** 2018-10-08 03:31 UTC
Labels: 2.1.1, bugsnag, production
